/**
 * Generate WireGuard peer configurations locally
 * Creates two matching peer configs that can connect to each other on localhost
 * 
 * Note: This generates configs with random keys. For actual WireGuard connections,
 * you need valid Curve25519 key pairs. The backend will need to use 'wg genkey' and 'wg pubkey'
 * to generate real keys, or we can call the backend to generate them.
 */

// Generate a random base64-encoded key (WireGuard keys are 32 bytes, base64 encoded = 44 chars)
// NOTE: These are NOT valid WireGuard keys - they're placeholders
// Real WireGuard requires Curve25519 keys generated by 'wg genkey' and 'wg pubkey'
function generateWireGuardKey(): string {
  // Generate 32 random bytes and encode to base64
  const array = new Uint8Array(32);
  crypto.getRandomValues(array);
  // Convert to base64 (WireGuard format)
  const base64 = btoa(String.fromCharCode(...array));
  return base64;
}

// Generate key pair (placeholder - not valid for real WireGuard)
// For real connections, keys must be generated server-side using wg commands
function generateKeyPair(): { privateKey: string; publicKey: string } {
  const privateKey = generateWireGuardKey();
  // In a real implementation, this would use Curve25519 scalar multiplication
  // For simulation, we'll generate a matching public key
  const publicKey = generateWireGuardKey();
  return { privateKey, publicKey };
}

export interface GeneratedConfigs {
  configA: string;
  configB: string;
  peerA_IP: string;
  peerB_IP: string;
  usedPlaceholderKeys: boolean;
}

export async function generatePeerConfigs(options?: {
  machineA_IP?: string;
  machineB_IP?: string;
  useLocalhost?: boolean;
}): Promise<GeneratedConfigs> {
  // Generate valid WireGuard key pairs using backend (wg genkey/wg pubkey)
  let peerAKeys, peerBKeys;
  let usedPlaceholderKeys = false;
  try {
    const { generateWireGuardKeyPairs } = await import('../apiService');
    const keys = await generateWireGuardKeyPairs();
    peerAKeys = keys.peerA;
    peerBKeys = keys.peerB;
  } catch (error) {
    console.warn('Backend unavailable or key generation failed, using placeholder keys');
    peerAKeys = generateKeyPair();
    peerBKeys = generateKeyPair();
    usedPlaceholderKeys = true;
  }
  
  // Assign IPs from 10.0.8.0/24 range
  const peerA_IP = '10.0.8.1/24';
  const peerB_IP = '10.0.8.2/24';
  const peerA_Address = peerA_IP.split('/')[0];
  const peerB_Address = peerB_IP.split('/')[0];
  
  // Determine endpoint IPs
  // If machine IPs are provided, use them; otherwise use localhost
  const useLocalhost = options?.useLocalhost ?? (!options?.machineA_IP && !options?.machineB_IP);
  const machineA_Endpoint = useLocalhost ? '127.0.0.1' : (options?.machineA_IP || '127.0.0.1');
  const machineB_Endpoint = useLocalhost ? '127.0.0.1' : (options?.machineB_IP || '127.0.0.1');
  
  // Generate configuration for Peer A
  const configA = `[Interface]
PrivateKey = ${peerAKeys.privateKey}
Address = ${peerA_IP}
ListenPort = 51820

[Peer]
PublicKey = ${peerBKeys.publicKey}
Endpoint = ${machineB_Endpoint}:51821
AllowedIPs = ${peerB_Address}/32
PersistentKeepalive = 25
`;

  // Generate configuration for Peer B
  const configB = `[Interface]
PrivateKey = ${peerBKeys.privateKey}
Address = ${peerB_IP}
ListenPort = 51821

[Peer]
PublicKey = ${peerAKeys.publicKey}
Endpoint = ${machineA_Endpoint}:51820
AllowedIPs = ${peerA_Address}/32
PersistentKeepalive = 25
`;

  return {
    configA,
    configB,
    peerA_IP,
    peerB_IP,
    usedPlaceholderKeys,
  };
}
