#!/bin/bash
# Setup passwordless sudo for WireGuard operations
# Run this script once to configure sudo permissions

echo "Setting up passwordless sudo for WireGuard operations..."

# Get the current user
CURRENT_USER=$(whoami)

# Get the project directory (where this script is located)
PROJECT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# Create sudoers file for WireGuard commands
SUDOERS_FILE="/etc/sudoers.d/wireguard-${CURRENT_USER}"

echo "Setting up passwordless sudo for WireGuard operations..."
echo "User: $CURRENT_USER"
echo "Project directory: $PROJECT_DIR"
echo "Creating sudoers file: $SUDOERS_FILE"
echo ""

# Create the sudoers entry
sudo tee "$SUDOERS_FILE" > /dev/null <<EOF
# Allow $CURRENT_USER to run WireGuard commands without password
# Generated by setup-sudo.sh from $PROJECT_DIR

$CURRENT_USER ALL=(ALL) NOPASSWD: /usr/bin/wg-quick *
$CURRENT_USER ALL=(ALL) NOPASSWD: /bin/mkdir -p /etc/wireguard
$CURRENT_USER ALL=(ALL) NOPASSWD: /bin/chmod 755 /etc/wireguard
$CURRENT_USER ALL=(ALL) NOPASSWD: /bin/chmod 600 /etc/wireguard/*
$CURRENT_USER ALL=(ALL) NOPASSWD: /bin/cp $PROJECT_DIR/wg*.conf.tmp /etc/wireguard/*
$CURRENT_USER ALL=(ALL) NOPASSWD: /usr/bin/ip link show wg*
$CURRENT_USER ALL=(ALL) NOPASSWD: /usr/bin/wg show *
EOF

# Set proper permissions on sudoers file
sudo chmod 0440 "$SUDOERS_FILE"

echo ""
echo "✓ Sudoers file created successfully!"
echo ""
echo "Testing sudo access..."
echo "You may be prompted for your password one last time:"

# Test the commands
sudo -n mkdir -p /etc/wireguard 2>/dev/null && echo "✓ mkdir works" || echo "✗ mkdir still requires password"
sudo -n wg-quick --version >/dev/null 2>&1 && echo "✓ wg-quick works" || echo "✗ wg-quick still requires password"

echo ""
echo "Setup complete! You should now be able to run WireGuard commands without password."
echo "If commands still require password, you may need to log out and log back in."

